routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'FrontController@index');
Route::get('about', 'FrontController@about');
Route::get('services', 'FrontController@services');
Route::get('news', 'FrontController@articles')->name('front.articles');
Route::get('news/{news}/{title?}', 'FrontController@article')->name('front.article');
Route::get('faqbot/{category?}', 'FrontController@faqs')->name('front.faqs');
Route::get('faq/{category?}/{q?}', 'FrontController@faq')->name('front.faq');
Route::get('faq_search', function (Request $request) {
	return redirect()->route('front.faq', ['category' => $request->category, 'q' => $request->q]);
});
Route::get('dashboard', function () {
	return view('homepage');
})->middleware('auth');

Route::get('privacy', function () {
	return view('privacy');
});

Route::get('newsletter', function () {
	return view('newsletter');
});


Route::get('faqcsv', 'FaqBotController@exportCsv');

Route::get('/home', 'HomeController@index')->name('home');


// Facebook login
Route::get('facebook/redirect', 'SocialAuthFacebookController@redirect');
Route::get('callback', 'SocialAuthFacebookController@callback');





//Auth::routes();
Auth::routes(['verify' => true]);

//Route::get('/home', 'HomeController@index')->middleware('verified');

Route::middleware('auth')->group(function () {
	Route::resource('categories', 'CategoryController');

	Route::resource('changes', 'ChangeController');

	Route::resource('faqs', 'FaqController');

	Route::resource('merchants', 'MerchantController');

	Route::resource('products', 'ProductController');

	Route::resource('tags', 'TagController');

	Route::resource('workers', 'WorkerController');

	Route::resource('users', 'UserController');

	Route::resource('articles', 'ArticleController');
});


Route::resource('mailinglists', 'MailinglistController');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- CSRF Token -->
	<meta name="csrf-token" content="{{ csrf_token() }}">
	@yield('aimeos_header')

	<title>iGetBelle.com</title>

	<!-- Scripts -->
	<script src="{{ asset('js/app.js') }}" defer></script>

	<!-- Fonts -->
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

	<!-- Styles -->
	<link href="{{ asset('css/app.css') }}" rel="stylesheet">
	@yield('aimeos_styles')
</head>

<body>
	<div id="app">
		<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
			<div class="container">
				<a href="/"><img src="{{ asset('images/banner_small.png') }}" style="width: 120px;" alt="" /></a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<!-- Left Side Of Navbar -->
					<ul class="navbar-nav mr-auto">

					</ul>

					<!-- Right Side Of Navbar -->
					<ul class="navbar-nav ml-auto">
						<!-- Authentication Links -->
						@guest
						<li class="nav-item">
							<a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
						</li>
						@if (Route::has('register'))
						<li class="nav-item">
							<a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
						</li>
						@endif
						@else
						<li class="nav-item dropdown">
							<a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
								{{ Auth::user()->name }}
							</a>

							<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
								<a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
									{{ __('Logout') }}
								</a>

								<form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
									@csrf
								</form>
							</div>
						</li>
						@endguest
					</ul>
					@yield('aimeos_head')
				</div>
			</div>
		</nav>

		<main class="py-4">
			@yield('aimeos_nav')
			@yield('aimeos_stage')
			@yield('aimeos_body')
			@yield('aimeos_aside')
			@yield('content')
		</main>
	</div>

	<script src="https://cdn.jsdelivr.net/combine/npm/jquery@3,npm/bootstrap@4"></script>
	@yield('aimeos_scripts')

</body>

</html>

resources/views/layouts/app2.blade.php
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<title>iGetBelle Dashboard</title>
	<meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

	<!-- CSRF Token -->
	<meta name="csrf-token" content="{{ csrf_token() }}">

	<!-- Bootstrap 3.3.7 -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	<!-- Theme style -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/AdminLTE.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/skins/_all-skins.min.css">

	<!-- iCheck -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">

	<!-- Ionicons -->
	<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">

	@yield('css')
</head>

<body class="skin-black-light sidebar-mini">
	@if (!Auth::guest())
	<div class="wrapper">
		<!-- Main Header -->
		<header class="main-header">

			<!-- Logo -->
			<a href="/" class="logo">
				<img src="{{ asset('images/banner_small.png') }}" width="80" alt="igetbelle logo">
			</a>

			<!-- Header Navbar -->
			<nav class="navbar navbar-static-top" role="navigation">
				<!-- Sidebar toggle button-->
				<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
					<span class="sr-only">Toggle navigation</span>
				</a>
				<!-- Navbar Right Menu -->
				<div class="navbar-custom-menu">
					<ul class="nav navbar-nav">
						<!-- User Account Menu -->
						<li class="dropdown user user-menu">
							<!-- Menu Toggle Button -->
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<!-- The user image in the navbar-->
								<img src="{{ asset('img/avatar.png') }}" class="user-image" alt="User Image" />
								<!-- hidden-xs hides the username on small devices so only the image appears. -->
								<span class="hidden-xs">{{ Auth::user()->name }}</span>
							</a>
							<ul class="dropdown-menu">
								<!-- The user image in the menu -->
								<li class="user-header">
									<img src="{{ asset('img/avatar.png') }}" class="img-circle" alt="User Image" />
									<p>
										{{ Auth::user()->name }}
										<small>Member since {{ Auth::user()->created_at->format('M. Y') }}</small>
									</p>
								</li>
								<!-- Menu Footer-->
								<li class="user-footer">
									<div class="pull-left">
										<a href="#" class="btn btn-default btn-flat">Profile</a>
									</div>
									<div class="pull-right">
										<a href="{{ url('/logout') }}" class="btn btn-default btn-flat" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
											Sign out
										</a>
										<form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
											@csrf
										</form>
									</div>
								</li>
							</ul>
						</li>
					</ul>
				</div>
			</nav>
		</header>

		<!-- Left side column. contains the logo and sidebar -->
		@include('layouts.sidebar')
		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			@yield('content')
		</div>

		<!-- Main Footer -->
		<footer class="main-footer" style="max-height: 100px;text-align: center">
			<strong>Copyright © 2020 <a href="/">iGetBelle</a>.</strong> All rights reserved.
		</footer>

	</div>
	@else
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<div class="navbar-header">

				<!-- Collapsed Hamburger -->
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>

				<!-- Branding Image -->
				<a href="/" class="logo">
					<img src="{{ asset('images/banner_small.png') }}" width="80" alt="igetbelle logo">
				</a>
			</div>

			<div class="collapse navbar-collapse" id="app-navbar-collapse">
				<!-- Right Side Of Navbar -->
				<ul class="nav navbar-nav navbar-right">
					<!-- Authentication Links -->
					<li><a href="{{ url('/login') }}">Login</a></li>
					<li><a href="{{ url('/register') }}">Register</a></li>
				</ul>
			</div>
		</div>
	</nav>

	<div id="page-content-wrapper">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					@yield('content')
				</div>
			</div>
		</div>
	</div>
	@endif

	<!-- jQuery 3.1.1 -->
	<!--
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
-->
	<script src="{{ asset('js/jquery.min.js') }}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
	<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
	<!-- AdminLTE App -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/js/adminlte.min.js"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>

	<script src="https://cdn.tiny.cloud/1/bqfoxvymeu8h31u5yontgd8tbllh4gwyyibobg31ny927inm/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
	<script>
		tinymce.init({
			selector: 'textarea',
			plugins: 'wordcount emoticons fullscreen lists',
			toolbar: 'wordcount emoticons fullscreen numlist bullist',
		});
	</script>

	@stack('scripts')
</body>


</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/header.blade.php
<header class="header" id="header">
	<div>
		<div class="header_top">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="header_top_content d-flex flex-row align-items-center justify-content-start">
							<div class="logo">
								<a href="#"><img src="{{ asset('images/banner_small.png') }}" style="width: 120px;" alt="" /></a>
							</div>
							<div class="header_top_extra d-flex flex-row align-items-center justify-content-start ml-auto">
								<div class="header_top_nav">
									<ul class="d-flex flex-row align-items-center justify-content-start">
										<li><a href="{{ route('front.faq') }}">Frequently Asked Questions</a></li>
										<li><a href="{{ url('/') }}#login">Daily Tracker</a></li>
										<li><a href="#">Get a Doctor</a></li>
									</ul>
								</div>
								<div class="header_top_phone">
									@auth

									<a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
										<img src="{{ asset('images/logout.png') }}" alt="logout">
									</a>

									<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
										{{ csrf_field() }}
									</form>
									@endauth
									@guest
									<a href="{{ url('home') }}">
										<img src="{{ asset('images/login.png') }}" alt="login" style="max-width:50px;">
									</a>
									@endguest
								</div>
							</div>
							<div class="hamburger ml-auto">
								<i class="fa fa-bars" aria-hidden="true"></i>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header_nav" id="header_nav_pin">
			<div class="header_nav_inner">
				<div class="header_nav_container">
					<div class="container">
						<div class="row">
							<div class="col">
								<div class="header_nav_content d-flex flex-row align-items-center justify-content-start">
									<nav class="main_nav">
										<ul class="d-flex flex-row align-items-center justify-content-start">
											<li>
												<a href="{{ url('/') }}">Home</a>
											</li>
											<li><a href="{{ url('about') }}">About Us</a></li>
											<li><a href="{{ url('services') }}">Services</a></li>
											<li><a href="{{ route('front.articles') }}">Articles</a></li>
										</ul>
										@yield('aimeos_head')
									</nav>
									<div class="search_content d-flex flex-row align-items-center justify-content-end ml-auto">
										<form action="#" id="search_container_form" class="search_container_form">
											<input type="text" class="search_container_input" placeholder="Search" required="required" />
											<button class="search_container_button">
												<i class="fa fa-search" aria-hidden="true"></i>
											</button>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>

resources/views/layouts/homenav.blade.php
	<div class="super_container">
		<!-- Menu -->

		<div class="menu trans_500">
			<div class="menu_content d-flex flex-column align-items-center justify-content-center text-center">
				<div class="menu_close_container">
					<div class="menu_close"></div>
				</div>
				<form action="#" class="menu_search_form">
					<input type="text" class="menu_search_input" placeholder="Search" required="required" />
					<button class="menu_search_button">
						<i class="fa fa-search" aria-hidden="true"></i>
					</button>
				</form>
				<ul>
					<li class="menu_item"><a href="{{ url('/') }}">home</a></li>
					<li class="menu_item"><a href="{{ url('about') }}">about us</a></li>
					<li class="menu_item"><a href="{{ url('services') }}">services</a></li>
					<li class="menu_item"><a href="{{ route('front.articles') }}">articles</a></li>
				</ul>
			</div>
			<div class="menu_social">
				<ul>
					<li>
						<a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
					</li>
					<li>
						<a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
					</li>
					<li>
						<a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
					</li>
					<li>
						<a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
					</li>
				</ul>
			</div>
		</div>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-179841017-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];

		function gtag() {
			dataLayer.push(arguments);
		}
		gtag('js', new Date());

		gtag('config', 'UA-179841017-1');
	</script>
	@yield('title')
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<!-- CSRF Token -->
	<meta name="csrf-token" content="{{ csrf_token() }}">
	@yield('aimeos_header')
	<link href="{{ asset('images/favicon.png') }}" rel="icon" />
	<link rel="stylesheet" type="text/css" href="{{ asset('styles/bootstrap4/bootstrap.min.css') }}" />
	<link href="{{ asset('plugins/font-awesome-4.7.0/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" type="text/css" href="{{ asset('plugins/OwlCarousel2-2.2.1/owl.carousel.css') }}" />
	<link rel="stylesheet" type="text/css" href="{{ asset('plugins/OwlCarousel2-2.2.1/owl.theme.default.css') }}" />
	<link rel="stylesheet" type="text/css" href="{{ asset('plugins/OwlCarousel2-2.2.1/animate.css') }}" />
	@yield('css')
	@yield('aimeos_styles')
</head>

<body>
	@yield('aimeos_nav')
	@yield('aimeos_stage')
	@yield('aimeos_body')
	@yield('aimeos_aside')
	@yield('content')

	<footer class="footer">
		<div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{{ asset('images/footer.jpg') }}" data-speed="0.8"></div>
		<div class="footer_content">
			<div class="container">
				<div class="row">
					<!-- Footer About -->
					<div class="col-lg-3 footer_col">
						<div class="footer_about">
							<div class="logo">
								<a href="/"><img src="{{ asset('images/banner_small.png') }}" style="width: 120px;" alt="" /></a>
							</div>
							<div class="footer_about_text">
								Have questions about pregnancy? Find answers at <strong>iGetBelle.com</strong>, with real doctor vetted facts.
							</div>
							<div class="footer_social">
								<ul class="d-flex flex-row align-items-center justify-content-start">
									<li>
										<a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
									</li>
									<li>
										<a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
									</li>
									<li>
										<a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
									</li>
									<li>
										<a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
									</li>
								</ul>
							</div>
						</div>
					</div>

					<!-- Footer Contact -->
					<div class="col-lg-5 footer_col">
						<div class="footer_contact">
							<iframe width="540" height="400" src="{{ url('newsletter') }}" frameborder="0" scrolling="no" allowfullscreen style="display: block;margin-left: auto;margin-right: auto;max-width: 100%;"></iframe>
						</div>
					</div>

					<!-- Footer Hours -->
					<div class="col-lg-4 footer_col">
						<div class="footer_hours">
							<div class="footer_hours_title">Statistics</div>
							<ul class="hours_list">
								<li class="d-flex flex-row align-items-center justify-content-start">
									<div>Languages Covered</div>
									<div class="ml-auto">3</div>
								</li>
								<li class="d-flex flex-row align-items-center justify-content-start">
									<div>Countries Covered</div>
									<div class="ml-auto">10</div>
								</li>
								<li class="d-flex flex-row align-items-center justify-content-start">
									<div>Vetted Posts</div>
									<div class="ml-auto">86,722</div>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="footer_bar">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="footer_bar_content d-flex flex-sm-row flex-column align-items-lg-center align-items-start justify-content-start">
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							Copyright &copy; 2020 -
							<script>
								document.write(new Date().getFullYear());
							</script>
							, Otomatik Ventures.
							All rights reserved | <a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>
	</div>

	<script src="https://cdn.jsdelivr.net/combine/npm/jquery@3,npm/bootstrap@4"></script>
	@yield('aimeos_scripts')
	<script src="{{ asset('styles/bootstrap4/popper.js') }}"></script>
	<script src="{{ asset('plugins/OwlCarousel2-2.2.1/owl.carousel.js') }}"></script>
	<script src="{{ asset('plugins/easing/easing.js') }}"></script>
	<script src="{{ asset('plugins/parallax-js-master/parallax.min.js') }}"></script>
	@stack('js')
</body>


</html>

resources/views/layouts/menu.blade.php
@if(Auth::user()->roleId == 1)
<li class="{{ Request::is('changes*') ? 'active' : '' }}">
	<a href="{{ route('changes.index') }}"><i class="fa fa-edit"></i><span>Changes</span></a>
</li>

<li class="{{ Request::is('merchants*') ? 'active' : '' }}">
	<a href="{{ route('merchants.index') }}"><i class="fa fa-edit"></i><span>Merchants</span></a>
</li>

<li class="{{ Request::is('products*') ? 'active' : '' }}">
	<a href="{{ route('products.index') }}"><i class="fa fa-edit"></i><span>Products</span></a>
</li>


<li class="{{ Request::is('workers*') ? 'active' : '' }}">
	<a href="{{ route('workers.index') }}"><i class="fa fa-edit"></i><span>Workers</span></a>
</li>

<li class="{{ Request::is('users*') ? 'active' : '' }}">
	<a href="{{ route('users.index') }}"><i class="fa fa-edit"></i><span>Users</span></a>
</li>
@endif








@if(Auth::user()->roleId <= 2) <li class="{{ Request::is('faqs*') ? 'active' : '' }}">
	<a href="{{ route('faqs.index') }}"><i class="fa fa-edit"></i><span>FAQs</span></a>
	</li>

	<li class="{{ Request::is('tags*') ? 'active' : '' }}">
		<a href="{{ route('tags.index') }}"><i class="fa fa-edit"></i><span>Tags</span></a>
	</li>

	<li class="{{ Request::is('categories*') ? 'active' : '' }}">
		<a href="{{ route('categories.index') }}"><i class="fa fa-edit"></i><span>Categories</span></a>
	</li>
	<li class="{{ Request::is('articles*') ? 'active' : '' }}">
		<a href="{{ route('articles.index') }}"><i class="fa fa-edit"></i><span>Articles</span></a>
	</li>

	<li class="{{ Request::is('mailinglists*') ? 'active' : '' }}">
		<a href="{{ route('mailinglists.index') }}"><i class="fa fa-edit"></i><span>Mailinglists</span></a>
	</li>
	@endif

	<hr>

	<li class="{{ Request::is('mailinglists*') ? 'active' : '' }}">
		<a href="{{ url('faqcsv') }}">Download CSV</a>
	</li>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

	<!-- sidebar: style can be found in sidebar.less -->
	<section class="sidebar">

		<!-- Sidebar user panel (optional) -->
		<div class="user-panel">
			<div class="pull-left image">
				<img src="{{ asset('img/avatar.png') }}" class="img-circle" alt="User Image" />
			</div>
			<div class="pull-left info">
				@if (Auth::guest())
				<p>iGetBelle</p>
				@else
				<p>{{ Auth::user()->name}}</p>
				@endif
				<!-- Status -->
				<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
			</div>
		</div>

		<!-- search form (Optional) -->
		<form action="#" method="get" class="sidebar-form">
			<div class="input-group">
				<input type="text" name="q" class="form-control" placeholder="Search..." />
				<span class="input-group-btn">
					<button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
					</button>
				</span>
			</div>
		</form>
		<!-- Sidebar Menu -->

		<ul class="sidebar-menu" data-widget="tree">
			@include('layouts.menu')
		</ul>
		<!-- /.sidebar-menu -->
	</section>
	<!-- /.sidebar -->
</aside>